---
name: Path To Live

on:
  push:
#    branches-ignore: [main]

#  pull_request:
#    branches: [main]

jobs:
  lint:
    name: Lint Code Base
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Lint Code Base
        uses: github/super-linter@v4
        env:
          VALIDATE_ALL_CODEBASE: false
          DEFAULT_BRANCH: master
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    test:
      name: Unit testing
      needs:
        - lint
      runs-on: ubuntu-latest

      steps:
        - name: Checkout Code
          uses: actions/checkout@v3

        - name: Run composer
          run: composer require phpunit/phpunit

        - name: run unit tests
          run: php vendor/bin/phpunit tests/
